[project]
name = "circfit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "networkx>=3.6.1",
    "numpy>=2.4.3",
    "scipy-stubs[scipy]>=1.17.1.1",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "types-networkx>=3.6.1.20260303",
]
